Seq <- c("ATGTCTGATAATGGACCCCAAAATCAGCGAAATGCACCCCGCATTACGTTTGGTGGACCCTCAGATTCAA
CTGGCAGTAACCAGAATGGAGAACGCAGTGGGGCGCGATCAAAACAACGTCGGCCCCAAGGTTTACCCAA
TAATACTGCGTCTTGGTTCACCGCTCTCACTCAACATGGCAAGGAAGACCTTAAATTCCCTCGAGGACAA
GGCGTTCCAATTAACACCAATAGCAGTCCAGATGACCAAATTGGCTACTACCGAAGAGCTACCAGACGAA
TTCGTGGTGGTGACGGTAAAATGAAAGATCTCAGTCCAAGATGGTATTTCTACTACCTAGGAACTGGGCC
AGAAGCTGGACTTCCCTATGGTGCTAACAAAGACGGCATCATATGGGTTGCAACTGAGGGAGCCTTGAAT
ACACCAAAAGATCACATTGGCACCCGCAATCCTGCTAACAATGCTGCAATCGTGCTACAACTTCCTCAAG
GAACAACATTGCCAAAAGGCTTCTACGCAGAAGGGAGCAGAGGCGGCAGTCAAGCCTCTTCTCGTTCCTC
ATCACGTAGTCGCAACAGTTCAAGAAATTCAACTCCAGGCAGCAGTAGGGGAACTTCTCCTGCTAGAATG
GCTGGCAATGGCGGTGATGCTGCTCTTGCTTTGCTGCTGCTTGACAGATTGAACCAGCTTGAGAGCAAAA
TGTCTGGTAAAGGCCAACAACAACAAGGCCAAACTGTCACTAAGAAATCTGCTGCTGAGGCTTCTAAGAA
GCCTCGGCAAAAACGTACTGCCACTAAAGCATACAATGTAACACAAGCTTTCGGCAGACGTGGTCCAGAA
CAAACCCAAGGAAATTTTGGGGACCAGGAACTAATCAGACAAGGAACTGATTACAAACATTGGCCGCAAA
TTGCACAATTTGCCCCCAGCGCTTCAGCGTTCTTCGGAATGTCGCGCATTGGCATGGAAGTCACACCTTC
GGGAACGTGGTTGACCTACACAGGTGCCATCAAATTGGATGACAAAGATCCAAATTTCAAAGATCAAGTC
ATTTTGCTGAATAAGCATATTGACGCATACAAAACATTCCCACCAACAGAGCCTAAAAAGGACAAAAAGA
AGAAGGCTGATGAAACTCAAGCCTTACCGCAGAGACAGAAGAAACAGCAAACTGTGACTCTTCTTCCTGC
TGCAGATTTGGATGATTTCTCCAAACAATTGCAACAATCCATGAGCAGTGCTGACTCAACTCAGGCCTAA")

install.packages("BiocManager")
install(c("genbankr","Biostrings","ggtree","annotate")) 
install.packages(c("reshape2","rentrez"))

library(BiocManager)
library(genbankr)
library(rentrez)
library(annotate)
library(ape)
library(muscle)
library(reshape2)
library(ggtree)

HsBLAST<-blastSequences(paste(Seq),as = 'data.frame',
                           hitListSize = 40, timeout = 600)

HsHitsDF<-data.frame(ID=HsBLAST$Hit_accession,Seq=HsBLAST$Hsp_hseq,
             stringsAsFactors = FALSE)

as.character(HsHitsDF)

str(HsHitsDF)

HsHitsDF[HsHitsDF$ID=="MN994468",]
HsHitsDNA<-sapply(HsHitsDF$Seq,strsplit,split="")
names(HsHitsDNA)<-paste(1:nrow(HsHitsDF),HsHitsDF$ID,sep="_")
HsHitsDNA<-as.DNAbin(HsHitsDNA)
HsAlign<-muscle(HsHitsDNA,quiet=F)

checkAlignment(HsAlign[1:20,1:100],what=1)
checkAlignment(HsAlign[21:40,1:100],what=1)
checkAlignment(HsAlign, what=3)

SeqLen<-as.numeric(lapply(HsHitsDNA,length))
library(ggplot2)
qplot(SeqLen)+theme_bw()

HsDM<-dist.dna(HsAlign, model="K80")
class(HsDM)

HsDMmat<-as.matrix(HsDM)
dim(HsDMmat)


HsTree<-nj(HsDM)
str(HsTree)
class(HsTree)
ggtree(HsTree,, branch.length = "none", layout = "circular")

HsHitSeqs<-read.GenBank(HsBLAST$Hit_accession[1:3])
attr(HsHitSeqs, "species")
